### ISSUE TITLE
Issue with multi line string

### ISSUE THREAD

**Issue by Nova38** [mrob95/vscode-TalonScript#8]
The following is an example from the talon.wiki. The syntax highlighting seems to break after the multi line string

```talon
# Comments must be on their own line (optionally preceeded by whitespace)
some [<user.letter>] command:
    # or operator is used to deal with optional or alternative command parts. It works as the null
    # coalescing operator, not like boolean or.
    letter_defaulted = letter or "default"

    # Local variable assignment
    a = 2.2
    b = "foo"
    c = "interpolate the {letter_defaulted} and {b} variables into the string"
    c = """
    multiline string
    """
    # Only a single mathematical operation per line
    d = 2
    a = a + d
    a = a - d
    a = a * d
    a = a / d
    a = a % d

    # Sleep is a built in function and takes arguments of the (<float>|<integer><suffix>) form.
    # Float allows specifying (fractions) of a second. The <integer><suffix> form can be '1m', '5s', '500ms', '1000000us' etc.
    # Be aware sleeping in this way will prevent Talon from processing voice commands until the
    # sleep is over
    sleep(2s)

    # Repeats the previous line the given number of times, so in this case we'd sleep for a further 4 seconds
    repeat(2)

    # The key() action. Allows pressing, holding, and repeating individual key presses.
    # See the "key() action" wiki page for more details
    key(ctrl-f)

    insert("type in this literal string")
    auto_insert("process this string with the auto_format action, then type it in with insert()")

    # Stylistically we only recommend the following shorthand if it is the only action being
    # performed by the command.
    "type in this string using auto_insert()"
    """
    type in this
    multiline
    string using auto_insert()
    """

    # Call built in or user defined actions
    app.notify("show this in a notification balloon")
    user.grid_activate()
```

**Comment by Nova38** [comment]
It looks like the multi line string definition is here. 


https://github.com/mrob95/vscode-TalonScript/blob/master/syntaxes%2Ftalon.tmLanguage.yml#L129-L140

```yaml
  qstring-long:
    begin: ("""|''')
    end: (\1)
    name: string.quoted.double.talon
    beginCaptures:
      "1":
        name: punctuation.definition.string.begin.talon
    endCaptures:
      "1":
        name: punctuation.definition.string.end.talon
    patterns:
      - include: "#string-body"
```
